### ISSUE TITLE
特定のスレッド内からの投稿だと上手く勤怠打刻されない

### ISSUE THREAD

**Issue by satoshi-mayumi-LITALICO** [k2tzumi/hue-kintai-slask-command#22]
# 起きている事
- [福祉ソフト_litalico_勤怠_出](https://litalico-ceo-office.slack.com/archives/C02GUE43ZH8/p1687212043126439)のスレッド内で投稿すると、「おはようございます」スタンプは付くが、COMPANYを見ても打刻されていない
- [福祉ソフト_litalico_勤怠_退](https://litalico-ceo-office.slack.com/archives/C02GUE43ZH8/p1687216535994179)のスレッド内で投稿した場合「おつかれさまでした」スタンプが付き正しく打刻される

## 福祉ソフト_litalico_勤怠_出
打刻されない
<img width="814" alt="Monosnap かんたん請求_勤怠 - ceo-office - Slack 2023-06-20 19-27-32" src="https://github.com/k2tzumi/hue-kintai-slask-command/assets/61679459/32c90a07-345b-4989-8f87-8518b472b7d7">

## 福祉ソフト_litalico_勤怠_退
打刻される
<img width="822" alt="Monosnap かんたん請求_勤怠 - ceo-office - Slack 2023-06-20 19-29-27" src="https://github.com/k2tzumi/hue-kintai-slask-command/assets/61679459/08c2e2ca-c8f1-4b48-ae6e-f8fca50e8851">

# メモ
どのスレッドかによって挙動がかわるのか、それとも、出勤はダメだけど退勤はいけるのかは確認できていない。

**Comment by k2tzumi** [comment]
It looks like it's kind of working, so I'll close it.
Thanks for the report.
